// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/user/create": {
    params: {};
  };
  "/user/details": {
    params: {};
  };
  "/admin/expense": {
    params: {};
  };
  "/admin/details": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/user/create" | "/user/details" | "/admin/expense" | "/admin/details";
  };
  "./Welcome.tsx": {
    id: "Welcome";
    page: "/";
  };
  "./routes/ExpenseEntry.tsx": {
    id: "routes/ExpenseEntry";
    page: "/user/create";
  };
  "./routes/UserExpenseTable.tsx": {
    id: "routes/UserExpenseTable";
    page: "/user/details";
  };
  "./routes/AdminExpenseTable.tsx": {
    id: "routes/AdminExpenseTable";
    page: "/admin/expense";
  };
  "./routes/AdminExpenseDetails.tsx": {
    id: "routes/AdminExpenseDetails";
    page: "/admin/details";
  };
};