// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/user/create": {
    params: {};
  };
  "/user/view": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/user/create" | "/user/view";
  };
  "./Welcome.tsx": {
    id: "Welcome";
    page: "/";
  };
  "./routes/ExpenseEntry.tsx": {
    id: "routes/ExpenseEntry";
    page: "/user/create";
  };
  "./routes/UserExpenseTable.tsx": {
    id: "routes/UserExpenseTable";
    page: "/user/view";
  };
};